"use client";

import { motion } from "framer-motion";
import { Swords, RefreshCw, Copy, CheckCircle2, WifiOff } from "lucide-react";
import { useState, useCallback, useEffect, useRef } from "react";
import { useI18n } from "@/i18n/context";
import { generateNgram } from "@/lib/lmLabClient";

/* ─────────────────────────────────────────────
   Types
   ───────────────────────────────────────────── */

interface NgramGenerationBattleProps {
    /** Seed phrases to choose from or auto-cycle through */
    seeds?: string[];
    /** Which N values to show as columns (default: [1, 2, 3, 4]) */
    nValues?: number[];
    /** Max characters to generate per column (default: 80) */
    maxTokens?: number;
    /** Temperature for all generations (default: 0.8) */
    temperature?: number;
    /** If true, auto-generate on first scroll into view */
    autoGenerate?: boolean;
    /** Currently highlighted N value (lab mode) */
    highlightedN?: number;
}

type ColumnResult = {
    text: string;
    loading: boolean;
    error: string | null;
};

/* ─────────────────────────────────────────────
   Quality label color by N
   ───────────────────────────────────────────── */

const QUALITY_COLORS: Record<number, string> = {
    1: "text-red-400/60",
    2: "text-orange-400/60",
    3: "text-amber-400/60",
    4: "text-emerald-400/60",
};

/* ─────────────────────────────────────────────
   Typewriter text component
   ───────────────────────────────────────────── */

function TypewriterText({ seed, text }: { seed: string; text: string }) {
    return (
        <motion.div
            initial="hidden"
            animate="visible"
            variants={{
                hidden: {},
                visible: { transition: { staggerChildren: 0.018 } },
            }}
            className="font-mono text-sm leading-relaxed"
        >
            <span className="text-amber-300 font-bold">{seed}</span>
            {text.split("").map((ch, i) => (
                <motion.span
                    key={i}
                    variants={{
                        hidden: { opacity: 0 },
                        visible: { opacity: 1 },
                    }}
                    className="text-white/70"
                >
                    {ch}
                </motion.span>
            ))}
        </motion.div>
    );
}

/* ─────────────────────────────────────────────
   Copy button
   ───────────────────────────────────────────── */

function CopyButton({ text }: { text: string }) {
    const [copied, setCopied] = useState(false);
    const { t } = useI18n();
    const handleCopy = useCallback(async () => {
        try {
            await navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch { /* ignore */ }
    }, [text]);

    return (
        <button
            onClick={handleCopy}
            className="absolute top-2 right-2 p-1.5 rounded-md bg-black/40 border border-white/[0.06] opacity-0 group-hover/text:opacity-100 hover:border-amber-500/30 transition-all"
            title={t("ngramNarrative.generationBattle.copyToClipboard")}
        >
            {copied ? (
                <CheckCircle2 className="w-3 h-3 text-emerald-400" />
            ) : (
                <Copy className="w-3 h-3 text-white/40" />
            )}
        </button>
    );
}

/* ─────────────────────────────────────────────
   Main component
   ───────────────────────────────────────────── */

export function NgramGenerationBattle({
    seeds = ["the ", "I wa", "hello"],
    nValues = [1, 2, 3, 4],
    maxTokens = 80,
    temperature = 0.8,
    autoGenerate = false,
    highlightedN,
}: NgramGenerationBattleProps) {
    const { t } = useI18n();
    const [selectedSeed, setSelectedSeed] = useState(seeds[0]);
    const [results, setResults] = useState<Record<number, ColumnResult>>({});
    const [isGenerating, setIsGenerating] = useState(false);
    const hasAutoGenerated = useRef(false);
    const containerRef = useRef<HTMLDivElement>(null);

    const generateAll = useCallback(async () => {
        setIsGenerating(true);
        // Initialize all columns to loading
        const initial: Record<number, ColumnResult> = {};
        for (const n of nValues) {
            initial[n] = { text: "", loading: true, error: null };
        }
        setResults(initial);

        // Fire all requests in parallel
        const promises = nValues.map(async (n) => {
            try {
                const res = await generateNgram(selectedSeed, maxTokens, temperature, n);
                setResults((prev) => ({
                    ...prev,
                    [n]: { text: res.generated_text ?? "", loading: false, error: null },
                }));
            } catch (err) {
                setResults((prev) => ({
                    ...prev,
                    [n]: { text: "", loading: false, error: (err as Error).message },
                }));
            }
        });

        await Promise.all(promises);
        setIsGenerating(false);
    }, [nValues, selectedSeed, maxTokens, temperature]);

    // Auto-generate on first scroll into view
    useEffect(() => {
        if (!autoGenerate || hasAutoGenerated.current) return;
        const el = containerRef.current;
        if (!el) return;

        const observer = new IntersectionObserver(
            ([entry]) => {
                if (entry.isIntersecting && !hasAutoGenerated.current) {
                    hasAutoGenerated.current = true;
                    generateAll();
                    observer.disconnect();
                }
            },
            { threshold: 0.3 }
        );
        observer.observe(el);
        return () => observer.disconnect();
    }, [autoGenerate, generateAll]);

    const hasResults = Object.values(results).some((r) => r.text || r.loading);
    const allErrored = nValues.length > 0
        && nValues.every((n) => results[n]?.error)
        && !nValues.some((n) => results[n]?.loading);

    return (
        <div ref={containerRef} className="space-y-5">
            {/* Header row */}
            <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 rounded-xl bg-amber-500/15">
                        <Swords className="w-5 h-5 text-amber-300" />
                    </div>
                    <div>
                        <h4 className="text-sm font-bold text-white tracking-tight">
                            {t("ngramNarrative.generationBattle.title")}
                        </h4>
                        <p className="text-[10px] text-white/40 italic">
                            {t("ngramNarrative.generationBattle.subtitle")}
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-3">
                    {/* Seed selector */}
                    {seeds.length > 1 && (
                        <div className="flex items-center gap-2">
                            <span className="text-[10px] uppercase tracking-[0.15em] text-white/30 font-bold">
                                {t("ngramNarrative.generationBattle.seedLabel")}
                            </span>
                            <select
                                value={selectedSeed}
                                onChange={(e) => setSelectedSeed(e.target.value)}
                                disabled={isGenerating}
                                className="bg-black/40 border border-white/10 rounded-lg px-3 py-1.5 text-xs font-mono text-white/70 focus:outline-none focus:border-amber-500/40"
                            >
                                {seeds.map((s) => (
                                    <option key={s} value={s}>
                                        &quot;{s}&quot;
                                    </option>
                                ))}
                            </select>
                        </div>
                    )}

                    {/* Generate button */}
                    <motion.button
                        whileHover={{ scale: 1.03 }}
                        whileTap={{ scale: 0.97 }}
                        onClick={generateAll}
                        disabled={isGenerating}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-amber-500/15 hover:bg-amber-500/25 border border-amber-500/25 hover:border-amber-500/40 text-amber-300 text-xs font-bold uppercase tracking-wider transition-colors disabled:opacity-50"
                    >
                        {hasResults ? (
                            <>
                                <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? "animate-spin" : ""}`} />
                                {t("ngramNarrative.generationBattle.regenerateButton")}
                            </>
                        ) : (
                            t("ngramNarrative.generationBattle.generateButton")
                        )}
                    </motion.button>
                </div>
            </div>

            {/* Description */}
            <p className="text-xs text-white/40 leading-relaxed">
                {t("ngramNarrative.generationBattle.description")}
            </p>

            {/* All-error retry card */}
            {allErrored && (
                <motion.div
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="rounded-xl border border-red-500/20 bg-red-500/[0.04] p-6 text-center"
                >
                    <WifiOff className="w-6 h-6 text-red-400/60 mx-auto mb-3" />
                    <p className="text-sm text-white/50 mb-1">
                        Server may still be starting up
                    </p>
                    <p className="text-xs text-white/30 mb-4">
                        The backend takes ~20 seconds to wake from sleep.
                    </p>
                    <motion.button
                        whileHover={{ scale: 1.03 }}
                        whileTap={{ scale: 0.97 }}
                        onClick={generateAll}
                        className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-amber-500/15 hover:bg-amber-500/25 border border-amber-500/25 hover:border-amber-500/40 text-amber-300 text-xs font-bold uppercase tracking-wider transition-colors"
                    >
                        <RefreshCw className="w-3.5 h-3.5" />
                        Try again
                    </motion.button>
                </motion.div>
            )}

            {/* Columns grid */}
            {!allErrored && (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                    {nValues.map((n) => {
                        const col = results[n];
                        const isHighlighted = highlightedN === n;
                        const qualityKey = `ngramNarrative.generationBattle.qualityLabels.${n}` as const;
                        const qualityLabel = t(qualityKey);

                        return (
                            <motion.div
                                key={n}
                                initial={{ opacity: 0, y: 12 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: n * 0.06, duration: 0.4 }}
                                className={`rounded-xl border overflow-hidden transition-colors ${isHighlighted
                                    ? "border-amber-500/40 bg-amber-500/[0.04]"
                                    : "border-white/[0.08] bg-white/[0.02]"
                                    }`}
                            >
                                {/* Column header */}
                                <div className="flex items-center justify-between px-4 py-2.5 border-b border-white/[0.06]">
                                    <span className="inline-flex items-center px-2.5 py-1 rounded-md bg-amber-500/15 text-amber-300 border border-amber-500/30 font-mono text-xs font-bold">
                                        N = {n}
                                    </span>
                                    {col?.loading && (
                                        <span className="text-[10px] text-amber-300/50 animate-pulse">
                                            {t("ngramNarrative.generationBattle.streaming")}
                                        </span>
                                    )}
                                </div>

                                {/* Text area */}
                                <div className="bg-black/30 p-4 min-h-[120px] flex items-start relative group/text">
                                    {col?.loading ? (
                                        <div className="flex items-center gap-2">
                                            <div className="w-3 h-3 border-2 border-amber-400/30 border-t-amber-400 rounded-full animate-spin" />
                                            <span className="text-xs text-white/30">
                                                {t("ngramNarrative.generationBattle.streaming")}
                                            </span>
                                        </div>
                                    ) : col?.error ? (
                                        <p className="text-xs text-red-400/70">{col.error}</p>
                                    ) : col?.text ? (
                                        <TypewriterText seed={selectedSeed} text={col.text} />
                                    ) : (
                                        <p className="text-xs text-white/20 italic">
                                            {t("ngramNarrative.generationBattle.emptyState")}
                                        </p>
                                    )}
                                    {col?.text && !col.loading && (
                                        <CopyButton text={selectedSeed + col.text} />
                                    )}
                                </div>

                                {/* Quality label */}
                                <div className="px-4 py-2 border-t border-white/[0.04]">
                                    <p className={`text-[10px] uppercase tracking-[0.15em] font-bold ${QUALITY_COLORS[n] ?? "text-white/40"}`}>
                                        {qualityLabel}
                                    </p>
                                </div>
                            </motion.div>
                        );
                    })}
                </div>
            )}

            {/* Footer info */}
            <p className="text-[10px] text-white/20 text-center font-mono">
                {t("ngramNarrative.generationBattle.tokensLabel").replace("{count}", String(maxTokens))} · {temperature} {t("ngramNarrative.generationBattle.temperatureLabel")}
            </p>
        </div>
    );
}
